use std::path::{Path, PathBuf};

use tokio::fs;

use crate::error::{CliareError, Result};

#[derive(Debug, Clone)]
pub struct ArtifactGuideSummary {
    pub readme_path: PathBuf,
    pub agent_skill_path: PathBuf,
}

pub async fn write_measurement_guides(out_dir: &Path) -> Result<ArtifactGuideSummary> {
    write_guides(out_dir, measurement_readme(), measurement_agent_skill()).await
}

pub async fn write_benchmark_guides(out_dir: &Path) -> Result<ArtifactGuideSummary> {
    write_guides(out_dir, benchmark_readme(), benchmark_agent_skill()).await
}

async fn write_guides(
    out_dir: &Path,
    readme: &'static str,
    agent_skill: &'static str,
) -> Result<ArtifactGuideSummary> {
    let readme_path = out_dir.join("README.md");
    let agent_skill_path = out_dir.join("AGENT_SKILL.md");
    write_atomic(&readme_path, readme.as_bytes()).await?;
    write_atomic(&agent_skill_path, agent_skill.as_bytes()).await?;
    Ok(ArtifactGuideSummary {
        readme_path,
        agent_skill_path,
    })
}

async fn write_atomic(path: &Path, bytes: &[u8]) -> Result<()> {
    let temp_path = atomic_temp_path(path);
    fs::write(&temp_path, bytes)
        .await
        .map_err(|source| CliareError::WriteArtifactGuide {
            path: temp_path.clone(),
            source,
        })?;
    fs::rename(&temp_path, path)
        .await
        .map_err(|source| CliareError::WriteArtifactGuide {
            path: path.to_path_buf(),
            source,
        })?;
    Ok(())
}

fn atomic_temp_path(path: &Path) -> PathBuf {
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("artifact-guide");
    path.with_file_name(format!("{file_name}.tmp.{}", std::process::id()))
}

fn measurement_readme() -> &'static str {
    r#"# CLIARE Artifact Directory

This directory is a self-contained record of one CLIARE measurement. If `artifact-map.json` is present, start there for the folder map and navigation plan. Otherwise start with the scorecard for posture, the issue ledger for remediation, the command index for command-level navigation, and the evidence log for runtime proof.

## Files

| File | Purpose |
|---|---|
| `scorecard.json` | Score, subscores, findings, coverage pressure, precondition counts, output-contract counts, and side-effect counts. |
| `report.md` | Human-readable scorecard generated during measurement. |
| `summary.md` | CI summary suitable for job summaries and pull request checks. |
| `shape.json` | Inferred command tree, flags, output contracts, and shape gaps. |
| `command-index.json` | Command-centric agent index with one entry per command, parameters, preconditions, output contracts, suitability, and evidence pointers. |
| `command-index.md` | Human-readable command table derived from `command-index.json`. |
| `evidence.jsonl` | Append-only runtime event log. Every event has an `event_id`. |
| `findings.sarif` | SARIF findings for code-scanning style consumers. |
| `junit.xml` | JUnit summary for CI systems. |
| `measure-cache.json` | Fingerprint and profile cache used to avoid recomputing unchanged measurements. |
| `jobs/current` | Pointer to the latest measurement progress job. |
| `jobs/<job-id>.log` | Tail-friendly progress log with probe-budget percentage, scheduler messages, and artifact milestones. |
| `jobs/<job-id>.stdout.log` | Captured stdout for a detached measurement worker. |
| `jobs/<job-id>.stderr.log` | Captured stderr for a detached measurement worker. |
| `issues.json` | Reviewable issue ledger generated by measurement and refreshed by `cliare report <persona> --write`. |
| `issues.md` | Markdown version of the issue ledger. |
| `persona-*.json` | Persona-specific outcome packets generated by measurement. |
| `persona-*.md` | Persona-specific Markdown reports generated by measurement. |
| `AGENT_SKILL.md` | Agent workflow for triage, evidence lookup, and remediation planning. |
| `artifact-map.json` | Optional machine-readable folder map generated by `cliare describe . --write`. |
| `artifact-map.md` | Optional human-readable folder map generated by `cliare describe . --write`. |

## Fast Orientation

Use these commands from the artifact directory.

```sh
cliare jobs status --out .
```

```sh
cliare describe . --write
```

```sh
jq '{score:.score.total,status:.score.status,model:.score.model,measured_weight:.score.measured_weight,max_weight:.score.max_weight}' scorecard.json
```

```sh
jq '{commands_discovered:.coverage.commands_discovered,commands_runtime_confirmed:.coverage.commands_runtime_confirmed,confirmation_rate:.coverage.command_confirmation_rate,traversal_complete:.coverage.traversal_complete,frontier_remaining:.coverage.frontier_remaining,budget_exhausted:.coverage.budget_exhausted,observed_max_depth:.coverage.observed_max_depth,max_depth:.coverage.max_depth,probes_completed:.coverage.probes_completed,max_probes:.coverage.max_probes}' scorecard.json
```

```sh
jq '.findings[] | {id,severity,category,title,detail,recommendation}' scorecard.json
```

## Issue Triage

Refresh the issue ledger from existing measurement artifacts:

```sh
cliare report maintainer --out . --write
```

Refresh one persona packet for the reviewer who will act on the findings:

```sh
cliare report maintainer --out . --write
cliare report harness --out . --write
cliare report security --out . --write
```

Summarize the ledger:

```sh
jq '.summary, [.issues[] | {id,severity,category,confidence,title,affected:(.affected_commands|length)}]' issues.json
```

List pressing issues across the full ledger:

```sh
jq '[.issues[] | select(.severity=="critical" or .severity=="high" or .confidence=="needs_fixture") | {id,severity,category,confidence,title,affected_commands:(.affected_commands|length),evidence:(.evidence|length),recommendation,verification:.verification.command}]' issues.json
```

List pressing issues for one persona:

```sh
persona=security
jq '{persona:.persona,question:.primary_question,score:.summary.score,notes:.notes,top_issues:[.top_issues[] | {id,severity,category,confidence,title,recommendation,verification:.verification.command,affected_commands:(.affected_commands|length),evidence:(.evidence|length)}]}' "persona-${persona}.json"
```

List high-priority issues with the data needed to start work:

```sh
jq '.issues[] | select(.severity=="critical" or .severity=="high") | {id,severity,category,confidence,title,recommendation,verification,affected_commands:.affected_commands[0:10],evidence:.evidence[0:5]}' issues.json
```

Inspect one issue by id:

```sh
jq --arg id "issue.output_mode_unprobed" '.issues[] | select(.id==$id)' issues.json
```

Create a developer-ready issue packet:

```sh
jq --arg id "issue.output_mode_unprobed" '.issues[] | select(.id==$id) | {what:{id,title,impact,why_it_matters},severity,category,confidence,where:{commands:.affected_commands[0:10],evidence:.evidence[0:5]},how:{recommendation,verification}}' issues.json
```

The `confidence` field changes how to act:

| Confidence | Meaning | First action |
|---|---|---|
| `observed` | CLIARE directly observed the behavior. | Treat as a concrete defect or contract gap. |
| `blocked` | A runtime precondition blocked safe confirmation. | Decide whether help/catalog behavior should work before auth, config, or profile setup. |
| `needs_fixture` | CLIARE found a contract but needs safe operands or fixtures to validate it. | Add a fixture profile or document a safe validation command. |
| `inferred` | Evidence suggests a gap but direct confirmation is incomplete. | Improve help shape, command naming, or traversal budget before treating as a defect. |
| `advisory` | Non-blocking quality guidance. | Prioritize after concrete failures and blocked contracts. |

## Command and Contract Lookup

Find one command by path:

```sh
jq --arg path "adapter new" '.commands[] | select(.path == ($path | split(" "))) | {command,summary,runtime_state,agent_suitability,suitability_reasons,parameters,preconditions,output_contracts,gaps,evidence}' command-index.json
```

List commands by agent suitability:

```sh
jq '[.commands[] | {command,agent_suitability,runtime_state,preconditions,parameters,outputs:(.output_contracts|length),gaps:(.gaps|map(.kind))}] | group_by(.agent_suitability)[] | {suitability:.[0].agent_suitability,count:length,commands:[.[0:20][] | {command,runtime_state,preconditions,gaps}]}' command-index.json
```

List command gaps:

```sh
jq '.gaps[] | {kind,command_path,reason,evidence}' shape.json
```

List output contracts:

```sh
jq '.output_contracts[] | {path:.command_path,mode,flag_name,argv_fragment,probed,parse_success,precondition_blocked,diagnostic,help_behavior,help_diagnostic}' shape.json
```

Show output-contract issues with the command context and required fixtures:

```sh
jq '.issues[] | select(.id=="issue.output_mode_unprobed") | {title,recommendation,affected_commands:[.affected_commands[0:10][] | {path,argv,required_positionals,reason,output_contracts}]}' issues.json
```

## Evidence Lookup

Evidence references may include a suffix such as `e_000257:output mode layout row 17`. The event id is the part before the first colon.

```sh
ref="e_000257:output mode layout row 17"
event="${ref%%:*}"
jq --arg id "$event" 'select(.event_id==$id)' evidence.jsonl
```

Find process events that changed the sandbox filesystem:

```sh
jq -n '[inputs | select(.kind=="process_completed") | select((.payload.side_effects.total // 0) > 0) | {event_id,probe_id:.payload.probe_id,argv:.payload.argv,status:.payload.status,side_effects:{created:.payload.side_effects.created,modified:.payload.side_effects.modified,deleted:.payload.side_effects.deleted,total:.payload.side_effects.total,changes:.payload.side_effects.changes[0:5]}}][0:20]' evidence.jsonl
```

Find classified precondition blocks from the issue ledger:

```sh
jq '.issues[] | select(.confidence=="blocked") | {id,severity,category,title,recommendation,affected_commands:.affected_commands[0:10],evidence:.evidence[0:5]}' issues.json
```

Find candidate precondition diagnostics in raw process output:

```sh
jq -n '[inputs | select(.kind=="process_completed") | select(((.payload.stdout.text // "") + "\n" + (.payload.stderr.text // "")) | test("auth|required|login|profile|precondition"; "i")) | {event_id,probe_id:.payload.probe_id,argv:.payload.argv,status:.payload.status,stdout_lines:(.payload.stdout.text // "" | split("\n")[0:6]),stderr_lines:(.payload.stderr.text // "" | split("\n")[0:6])}][0:20]' evidence.jsonl
```

## Persona Reports

Use persona packets when the reviewer has a specific job:

```sh
cliare report maintainer --out . --write
cliare report harness --out . --write
cliare report platform --out . --write
cliare report security --out . --write
cliare report oss --out . --write
cliare report devrel --out . --write
cliare report research --out . --write
```

The persona files are summaries. The issue ledger is the working queue. The evidence log is the proof record.

## Persona Investigation Loop

Use this loop when turning artifacts into a reviewable work plan:

1. Open `artifact-map.json` if present, or run `cliare describe . --write`.
2. Open `persona-<persona>.md` for the role-specific brief.
3. Use `persona-<persona>.json` to list the top issues and their action language.
4. Use `issues.json` as the canonical work queue.
5. Use `command-index.json` or `command-index.md` as the command suitability table.
6. Use `shape.json` only when you need the raw inferred command tree, flags, output contracts, and shape gaps.
7. Use `evidence.jsonl` to prove what happened at runtime.
8. Produce findings in this shape: issue, severity, confidence, where it appears, why it matters, how to address it, and the verification command.

Persona focus:

| Persona | Primary question | First artifact |
|---|---|---|
| `maintainer` | What should change in the CLI? | `persona-maintainer.md` |
| `harness` | Which commands can agents safely route to? | `persona-harness.md` |
| `security` | What requires approval, restriction, or policy? | `persona-security.md` |
| `platform` | What should CI gate or warn on? | `persona-platform.md` |
| `oss` | What can be published credibly? | `persona-oss.md` |
| `devrel` | What should be explained publicly? | `persona-devrel.md` |
| `research` | What can be labeled or used for calibration? | `persona-research.md` |

When a report says `observed`, cite runtime evidence. When it says `blocked`, identify the precondition. When it says `needs_fixture`, define safe operands or a fixture. When it says `inferred`, do not call it a defect until command existence or behavior is confirmed.
"#
}

fn measurement_agent_skill() -> &'static str {
    include_str!("../skills/cliare-artifact-review/SKILL.md")
}

fn benchmark_readme() -> &'static str {
    r#"# CLIARE Benchmark Artifact Directory

This directory aggregates a CLIARE benchmark corpus run. Use it to compare multiple CLIs, track calibration, and navigate into each target's measurement artifacts.

## Files

| File | Purpose |
|---|---|
| `benchmark.json` | Machine-readable corpus result with totals, calibration metrics, and per-target status. |
| `benchmark.md` | Human-readable benchmark summary. |
| `<target-id>/` | Measurement artifact directory for a target that ran. Each target directory has its own `README.md` and `AGENT_SKILL.md`. |
| `AGENT_SKILL.md` | Agent workflow for benchmark review and target drill-down. |
| `artifact-map.json` | Optional machine-readable folder map generated by `cliare describe . --write`. |

## Fast Orientation

```sh
cliare describe . --write
```

## Corpus Summary

```sh
jq '{corpus,totals,calibration:{score_mean:.calibration.score_mean,score_min:.calibration.score_min,score_max:.calibration.score_max,expected_band_pass_rate:.calibration.expected_band_pass_rate,traversal_completion_rate:.calibration.traversal_completion_rate,budget_exhaustion_rate:.calibration.budget_exhaustion_rate}}' benchmark.json
```

## Target Ranking

```sh
jq '.targets[] | {id,status,score,expected_score,duration_ms,probes_completed,traversal_complete,budget_exhausted,observed_max_depth,max_depth,issues}' benchmark.json
```

Find targets outside their expected score band:

```sh
jq '.targets[] | select(.issues | length > 0) | {id,status,score,expected_score,issues,artifact_dir}' benchmark.json
```

Find large surfaces or budget pressure:

```sh
jq '.targets[] | select(.budget_exhausted==true or .traversal_complete==false) | {id,score,probes_completed,max_probes,observed_max_depth,max_depth,traversal_stop_reason,artifact_dir}' benchmark.json
```

## Drill Down

Move into a target artifact directory and use its local guide:

```sh
target_dir="$(jq -r '.targets[] | select(.id=="cliare") | .artifact_dir' benchmark.json)"
cd "$target_dir"
sed -n '1,220p' README.md
```

Refresh the target issue ledger when a focused review packet is needed:

```sh
cliare report maintainer --out "$target_dir" --write
```

Benchmark metrics explain corpus behavior. Target directories explain individual CLI behavior.
"#
}

fn benchmark_agent_skill() -> &'static str {
    r#"---
name: cliare-benchmark-review
description: Use when reviewing a CLIARE benchmark artifact directory, comparing CLI targets, explaining calibration metrics, or drilling into per-target measurement artifacts.
---

# CLIARE Benchmark Review

## What This Is

This is an artifact-local guide for an agent reviewing one CLIARE benchmark directory. A benchmark directory compares multiple CLI measurements, records corpus-level calibration metrics, and links each target back to its own measurement artifact directory.

Use it when the task is to explain a corpus run, compare targets, identify calibration drift, or decide which target artifact needs deeper review. Benchmark-level data shows comparative posture; target-level directories contain the evidence needed to recommend CLI changes.

Start at `benchmark.json`, then drill into target artifact directories for evidence.

## Workflow

1. Summarize corpus health.

```sh
jq '{totals,calibration:{score_mean:.calibration.score_mean,score_min:.calibration.score_min,score_max:.calibration.score_max,expected_band_pass_rate:.calibration.expected_band_pass_rate,traversal_completion_rate:.calibration.traversal_completion_rate,budget_exhaustion_rate:.calibration.budget_exhaustion_rate}}' benchmark.json
```

2. Rank targets by score and operational pressure.

```sh
jq '.targets[] | {id,status,score,expected_score,duration_ms,probes_completed,traversal_complete,budget_exhausted,observed_max_depth,max_depth,issues,artifact_dir}' benchmark.json
```

3. Separate benchmark failures from CLI findings. A benchmark target can fail because it missed an expected band, exceeded a duration budget, skipped a required binary, or produced CLIARE findings. Use the target `issues` field for benchmark-level failures and the target directory for CLI-level findings.

4. For a target that needs review, enter its `artifact_dir`, read `README.md`, then inspect `scorecard.json`, `issues.json`, `command-index.json`, `shape.json`, and `evidence.jsonl`.

```sh
target_dir="$(jq -r '.targets[] | select(.id=="cliare") | .artifact_dir' benchmark.json)"
cd "$target_dir"
jq '{score:.score.total,coverage:.coverage}' scorecard.json
```

5. Refresh persona reports inside the target directory when a reviewer needs a focused packet.

```sh
cliare report maintainer --out . --write
```

## Output Style

Report benchmark results as corpus-level trends first, then target-level evidence. Do not infer a target defect from a corpus metric alone. Use the target artifact directory before recommending a CLI change.
"#
}

#[cfg(test)]
mod tests {
    #[test]
    fn measurement_guide_contains_issue_and_evidence_queries() {
        let readme = super::measurement_readme();
        assert!(readme.contains("issues.json"));
        assert!(readme.contains("event=\"${ref%%:*}\""));
        assert!(readme.contains("scorecard.json"));
        assert!(readme.contains("command-index.json"));
        assert!(readme.contains("shape.json"));
        assert!(readme.contains("jobs/<job-id>.log"));
        assert!(readme.contains("Persona Investigation Loop"));
        assert!(readme.contains("affected_commands:.affected_commands[0:10]"));
        assert!(readme.contains("evidence:.evidence[0:5]"));
    }

    #[test]
    fn measurement_agent_skill_sets_review_workflow() {
        let skill = super::measurement_agent_skill();
        assert!(skill.contains("name: cliare-artifact-review"));
        assert!(skill.contains("confidence"));
        assert!(skill.contains("Avoid dumping entire JSON arrays"));
        assert!(skill.contains("Persona Lenses"));
        assert!(skill.contains("Deep dive one issue"));
        assert!(skill.contains("What the issue means in plain language"));
        assert!(skill.contains("Large Issue Lists"));
        assert!(skill.contains("Do not infer false positives"));
        assert!(skill.contains("Count affected commands by runtime state"));
    }

    #[test]
    fn benchmark_guide_points_to_target_artifacts() {
        let readme = super::benchmark_readme();
        assert!(readme.contains("benchmark.json"));
        assert!(readme.contains("artifact_dir"));
        assert!(readme.contains("README.md"));
    }
}
